settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: dev
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: rs-api
    # 端口号
    port: 8099 # 服务端口号
    readtimeout: 1
    writertimeout: 2
    # 数据权限功能开关
    enabledp: true
  logger:
    # 日志存放路径
    path: access/logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 操作数据库的记录开关
    enableddb: true
  jwt:
    # token 密钥，生产环境时及的修改
    secret: dynamic-store
    # token 过期时间 单位：秒
    #默认过期时间 5个小时
    timeout: 180000
  database:
    # 数据库类型 mysql, sqlite3, postgres, sqlserver
    # sqlserver: sqlserver://用户名:密码@地址?database=数据库名
    driver: mysql
    #    source: root:hzdcy.server@123#$@tcp(159.75.177.143:3306)/dynamic?charset=utf8&parseTime=True&loc=Local&timeout=8000ms
    #    source: root:hzdcy@123#$@tcp(152.136.36.253:3306)/dynamic?charset=utf8&parseTime=True&loc=Local&timeout=8000ms
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    #    source: root:chao930715@tcp(127.0.0.1:3306)/dynamic?charset=utf8&parseTime=True&loc=Local&timeout=8000ms
    source: root:@tcp(127.0.0.1:3306)/rs_store?charset=utf8&parseTime=True&loc=Local&timeout=8000ms
  gen:
    # 代码生成读取的数据库名称
    dbname: rs_store
    # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
    frontpath: ../go-admin-ui/src
  extend: # 扩展项使用说明

    pass: ""
  queue:
    memory:
      poolSize: 100
  locker:
    redis: